spring:
  application:
    name: Reimbursement_Service
  datasource:
    url: jdbc:postgresql://localhost:5432/Sentinel
    username: postgres
    password: Sharan@2005
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

cloudinary:
  cloud_name: "dmnqajo2n"
  api_key: "642842944939935"
  api_secret: "gPVAXUfxERYn8wKvQBYvpuS_ydM"

ocrBaseUrl: "http://localhost:8884/tesseract"