apiVersion: apps/v1
kind: Deployment
metadata:
  name: tesseract
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tesseract
  template:
    metadata:
      labels:
        app: tesseract
    spec:
      containers:
        - name: tesseract
          image: ghcr.io/hertzg/tesseract-server
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8884
---
apiVersion: v1
kind: Service
metadata:
  name: tesseract
spec:
  type: ClusterIP
  selector:
    app: tesseract
  ports:
    - port: 8884
      targetPort: 8884